### PR TITLE
Increase the power drawn in the ISO 15118-2 DC demo to 160 kW

### PR DESCRIPTION
**Pull request by drmrd**
The current ISO 15118-2 DC demo includes a charger configured to provide power to a simulated EV at a rate of roughly 6 kW. These changes modify the charger configuration to up this rate to 160 kW, which is more representative of a typical DC fast charging session.

### CODE REVIEW

**Comment by shankari** [comment]
@drmrd does this actually work? I believe it required a change to the image for it to work...

**Comment by drmrd** [comment]
@shankari: It does not without additional work. The `user-config` directory needs to be copied into `manager` during the build process.

@couryrr-afs: Can you push the `manager` update you refer to [here](https://github.com/US-JOET/everest-demo-private/pull/14#issuecomment-1777856606) that does this?

**Comment by couryrr-afs** [comment]
@drmrd should I be pushing a docker container? I can do so but it may become out of date if not automated with the CI/CD pipeline. I was having permission issues when doing attempting this previously.

**Comment by shankari** [comment]
@couryrr-afs as you can see from the current workflow, you should be able to rebuild containers by submitting a PR to a branch that starts with `build_pkg`. The CI/CD pipeline will build it in that case.
https://github.com/US-JOET/everest-demo/blob/main/.github/workflows/cicd.yaml

I think we should revisit even the current cicd pipeline to tag the images by date/time instead of branch, so that we can keep a single `build_pkg` branch sitting around to rebuild containers. And over the long-term, the build should really happen in the individual repos.
https://github.com/US-JOET/everest-demo-private/issues/16#issuecomment-1781556836

**Comment by couryrr-afs** [comment]
@drmrd  and @shankari it looks like this will push an image to the US-JOET. If we are okay with that for the time being then after this PR action runs the new image should have what is needed in the manager. The issue I was referring to was permission based for pushing images.

As for the image versioning there are various build and tagging strategy that we can use. As the the CI/CD pipeline matures we can implement those.

**Comment by shankari** [comment]
> it looks like this will push an image to the US-JOET. If we are okay with that

Yes, as outlined in the issue https://github.com/US-JOET/everest-demo-private/issues/16, this is the current process. We do not want the perfect to be the enemy of the good.

> after this PR action runs the new image should have what is needed in the manager.

To get the PR action to run, you will need to submit a PR to us-joet. Since this is a common theme across the PRs, I have created a new branch for this - `build_pkg_task_1_features`

> The issue I was referring to was permission based for pushing images.

images created by github actions automatically have permissions for pushing images

> As for the image versioning there are various build and tagging strategy that we can use. As the the CI/CD pipeline matures we can implement those.

Yes, there are various strategies. Can you open an issue and make a proposal on which one to use? The current flow works for the interim, but is clearly very clunky

**Comment by drmrd** [comment]
Waiting on an update with the correct `manager` `Dockerfile` and to set a correct image tag. Then this should be ready to be merged.

**Comment by drmrd** [comment]
@shankari: This PR should now be ready to merge.

**Pull request merged**
