### PR TITLE
Provide an ISO 15118-2 AC plus OCPP 1.6J demo

### PR DESCRIPTION
**Pull request by drmrd**
These changes include the addition of a new SteVe-based OCPP 1.6J demo that can be executed as a one-liner. Updates to the existing SteVe images (such as the one in the everest-utils repository) were made to obtain a SteVe server that operates well on macOS, Linux, and Windows.

Unfortunately, the build process for the SteVe image is not fully automated at this time. Fully automating it requires disabling or tracking CSRF tokens produced by the SteVe server.

The good news is that the build process is straightforward, with its only manual steps being configuring a charge point and several OCPP ID tags within SteVe before calling `docker commit` for the SteVe and OCPP DB containers. Instructions for the build process are captured in `steve/README.md`.

### CODE REVIEW

**Comment by drmrd** [comment]
Requesting a review from @shankari

**Comment by drmrd** [comment]
One note: This demo only works with manager images that include the changes from EVerest/everest-core#388. For instance, the version of `everest-core` pinned in the `manager` image in #8 is compatible with the OCPP 1.6J demo.

**Comment by shankari** [comment]
@drmrd since OCPP 1.6J integration will be deprecated soon anyway, and we are not rebuilding the images automatically,
I would suggest using the steve images (pre-built, `docker commit`ted) directly from US-JOET, and only use the everest containers (manager etc) from everest.

Once we have true end-to-end automated testing (including EV <-> EVSE <-> CSMS), we can include them as part of the smoke tests and know when to update the steve images (if necessary).

**Comment by shankari** [comment]
Merging, excited to finally see the end to end test working!

**Comment by shankari** [comment]
oh wait, I missed the 

> changes from https://github.com/EVerest/everest-demo/pull/6 are incorporated into this branch
> I'm happy to do this once we're otherwise ready to merge.

@drmrd when you are updating #6, you can apply the same changes to this docker-compose as well 😄

**Pull request merged**
