### PR TITLE
Updated README with SteVe web portal information

### PR DESCRIPTION
**Pull request by jhoshiko**
Edited readme to include a link to the SteVe web portal, added an image of the portal

### CODE REVIEW

**Comment by jhoshiko** [comment]
@shankari Here are the README updates. Small question about signing off on commits, I've used -s, and manually added both variations of my email (both are on my github profile). Not sure why I'm still getting flagged by DCO

**Comment by shankari** [comment]
@jhoshiko maybe the `Signed Off` line needs to be on one line.

**Comment by shankari** [comment]
The summary outlines the error

Commit sha: [656b7fd](https://github.com/EVerest/everest-demo/pull/16/commits/656b7fd7d1fa36036c5f10c90ec8d37e50458e9a), Author: jhoshiko, Committer: jhoshiko; jhoshiko is not a valid email address.

**Comment by jhoshiko** [comment]
Ok, I updated my signature in the git config and now it looks like it is working. I'm going to redirect you to this [fixed pr ](https://github.com/EVerest/everest-demo/pull/17)

**Pull request closed without merging**
